# Generated by Django 4.1.7 on 2023-04-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0005_employees_sexe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateHeure", models.DateTimeField(auto_now=True)),
                (
                    "etat",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Present(e)"), (2, "Retard"), (3, "Abscent(e)")]
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employees",
                    ),
                ),
            ],
        ),
    ]
