# Generated by Django 4.1.7 on 2023-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poste", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postes",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
