# Generated by Django 4.1.7 on 2023-03-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("poste", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Missions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=150)),
                (
                    "poste",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="poste.postes",
                    ),
                ),
            ],
        ),
    ]
