# Generated by Django 4.1.7 on 2023-03-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mission", "0001_initial"),
        ("poste", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                ("prenom", models.CharField(max_length=120)),
                ("date_de_naissance", models.DateField()),
                ("slug", models.SlugField()),
                ("date_embauche", models.DateField()),
                ("avatar", models.CharField(max_length=250)),
                ("mission", models.ManyToManyField(to="mission.missions")),
                (
                    "poste",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="poste.postes",
                    ),
                ),
            ],
        ),
    ]
