# Generated by Django 4.1.7 on 2023-03-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="mission",
        ),
    ]
