# Generated by Django 4.1.7 on 2023-04-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employees_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="slug",
        ),
    ]
