# Generated by Django 4.1.7 on 2023-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_remove_employees_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="sexe",
            field=models.BooleanField(null=True),
        ),
    ]
