# Generated by Django 4.1.7 on 2023-04-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0005_employees_sexe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(auto_now=True)),
                ("date_fin", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employees",
                    ),
                ),
            ],
        ),
    ]
