# Generated by Django 4.1.7 on 2023-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conges",
            name="enPoste",
            field=models.BooleanField(default=False),
        ),
    ]
